# Generated by Django 4.1 on 2022-08-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coment',
            table='coments',
        ),
    ]
