# Generated by Django 4.1 on 2022-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alias', models.CharField(max_length=56)),
                ('opinion', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
    ]
